name: rimapp_admin
description: "RimApp Admin App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6
  google_fonts: ^6.1.0
  intl: ^0.20.2
  fl_chart: ^0.65.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.0
  provider: ^6.1.1
  flutter_polyline_points: ^2.0.0
  google_maps_flutter: ^2.5.0
  google_directions_api: ^0.10.0
  http: ^1.1.0
  url_launcher: ^6.2.5
  shared_preferences: ^2.5.2
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#1E88E5"
  android_gravity: center
  ios_content_mode: center

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icon/icon.png
